services:
  web:
    build: .
    ports:
      - "8082:80"
    environment:
      SERVER_NAME: ":80"
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./profiling:/app/profiling
    working_dir: /app